/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedCertificatesRouteImport } from './routes/_authenticated/certificates'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedLiveQuizRouteImport } from './routes/_authenticated/live-quiz'
import { Route as AuthenticatedLogisticsRouteImport } from './routes/_authenticated/logistics'
import { Route as AuthenticatedOnlineQuizRouteImport } from './routes/_authenticated/online-quiz'
import { Route as AuthenticatedParticipantsRouteImport } from './routes/_authenticated/participants'
import { Route as AuthenticatedQuestionBankRouteImport } from './routes/_authenticated/question-bank'
import { Route as AuthenticatedScorekeeperRouteImport } from './routes/_authenticated/scorekeeper'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTeamsRouteImport } from './routes/_authenticated/teams'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events.$eventId'
import { Route as AuthenticatedQuestionBankIndexRouteImport } from './routes/_authenticated/question-bank.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCertificatesRoute =
  AuthenticatedCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLiveQuizRoute = AuthenticatedLiveQuizRouteImport.update({
  id: '/live-quiz',
  path: '/live-quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogisticsRoute = AuthenticatedLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnlineQuizRoute = AuthenticatedOnlineQuizRouteImport.update({
  id: '/online-quiz',
  path: '/online-quiz',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantsRoute =
  AuthenticatedParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankRoute =
  AuthenticatedQuestionBankRouteImport.update({
    id: '/question-bank',
    path: '/question-bank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScorekeeperRoute =
  AuthenticatedScorekeeperRouteImport.update({
    id: '/scorekeeper',
    path: '/scorekeeper',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionBankIndexRoute =
  AuthenticatedQuestionBankIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedQuestionBankRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/live-quiz': typeof AuthenticatedLiveQuizRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/online-quiz': typeof AuthenticatedOnlineQuizRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/question-bank': typeof AuthenticatedQuestionBankRouteWithChildren
  '/scorekeeper': typeof AuthenticatedScorekeeperRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/certificates': typeof AuthenticatedCertificatesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/live-quiz': typeof AuthenticatedLiveQuizRoute
  '/logistics': typeof AuthenticatedLogisticsRoute
  '/online-quiz': typeof AuthenticatedOnlineQuizRoute
  '/participants': typeof AuthenticatedParticipantsRoute
  '/scorekeeper': typeof AuthenticatedScorekeeperRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/question-bank': typeof AuthenticatedQuestionBankIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/certificates': typeof AuthenticatedCertificatesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/live-quiz': typeof AuthenticatedLiveQuizRoute
  '/_authenticated/logistics': typeof AuthenticatedLogisticsRoute
  '/_authenticated/online-quiz': typeof AuthenticatedOnlineQuizRoute
  '/_authenticated/participants': typeof AuthenticatedParticipantsRoute
  '/_authenticated/question-bank': typeof AuthenticatedQuestionBankRouteWithChildren
  '/_authenticated/scorekeeper': typeof AuthenticatedScorekeeperRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/question-bank/': typeof AuthenticatedQuestionBankIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/leaderboard'
    | '/live-quiz'
    | '/logistics'
    | '/online-quiz'
    | '/participants'
    | '/question-bank'
    | '/scorekeeper'
    | '/settings'
    | '/teams'
    | '/events/$eventId'
    | '/events/'
    | '/question-bank/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/analytics'
    | '/certificates'
    | '/dashboard'
    | '/leaderboard'
    | '/live-quiz'
    | '/logistics'
    | '/online-quiz'
    | '/participants'
    | '/scorekeeper'
    | '/settings'
    | '/teams'
    | '/events/$eventId'
    | '/events'
    | '/question-bank'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/certificates'
    | '/_authenticated/dashboard'
    | '/_authenticated/leaderboard'
    | '/_authenticated/live-quiz'
    | '/_authenticated/logistics'
    | '/_authenticated/online-quiz'
    | '/_authenticated/participants'
    | '/_authenticated/question-bank'
    | '/_authenticated/scorekeeper'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/events/'
    | '/_authenticated/question-bank/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/certificates': {
      id: '/_authenticated/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthenticatedCertificatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-quiz': {
      id: '/_authenticated/live-quiz'
      path: '/live-quiz'
      fullPath: '/live-quiz'
      preLoaderRoute: typeof AuthenticatedLiveQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics': {
      id: '/_authenticated/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof AuthenticatedLogisticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/online-quiz': {
      id: '/_authenticated/online-quiz'
      path: '/online-quiz'
      fullPath: '/online-quiz'
      preLoaderRoute: typeof AuthenticatedOnlineQuizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participants': {
      id: '/_authenticated/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof AuthenticatedParticipantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank': {
      id: '/_authenticated/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AuthenticatedQuestionBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scorekeeper': {
      id: '/_authenticated/scorekeeper'
      path: '/scorekeeper'
      fullPath: '/scorekeeper'
      preLoaderRoute: typeof AuthenticatedScorekeeperRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/question-bank/': {
      id: '/_authenticated/question-bank/'
      path: '/'
      fullPath: '/question-bank/'
      preLoaderRoute: typeof AuthenticatedQuestionBankIndexRouteImport
      parentRoute: typeof AuthenticatedQuestionBankRoute
    }
  }
}

interface AuthenticatedQuestionBankRouteChildren {
  AuthenticatedQuestionBankIndexRoute: typeof AuthenticatedQuestionBankIndexRoute
}

const AuthenticatedQuestionBankRouteChildren: AuthenticatedQuestionBankRouteChildren =
  {
    AuthenticatedQuestionBankIndexRoute: AuthenticatedQuestionBankIndexRoute,
  }

const AuthenticatedQuestionBankRouteWithChildren =
  AuthenticatedQuestionBankRoute._addFileChildren(
    AuthenticatedQuestionBankRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCertificatesRoute: typeof AuthenticatedCertificatesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLiveQuizRoute: typeof AuthenticatedLiveQuizRoute
  AuthenticatedLogisticsRoute: typeof AuthenticatedLogisticsRoute
  AuthenticatedOnlineQuizRoute: typeof AuthenticatedOnlineQuizRoute
  AuthenticatedParticipantsRoute: typeof AuthenticatedParticipantsRoute
  AuthenticatedQuestionBankRoute: typeof AuthenticatedQuestionBankRouteWithChildren
  AuthenticatedScorekeeperRoute: typeof AuthenticatedScorekeeperRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCertificatesRoute: AuthenticatedCertificatesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLiveQuizRoute: AuthenticatedLiveQuizRoute,
  AuthenticatedLogisticsRoute: AuthenticatedLogisticsRoute,
  AuthenticatedOnlineQuizRoute: AuthenticatedOnlineQuizRoute,
  AuthenticatedParticipantsRoute: AuthenticatedParticipantsRoute,
  AuthenticatedQuestionBankRoute: AuthenticatedQuestionBankRouteWithChildren,
  AuthenticatedScorekeeperRoute: AuthenticatedScorekeeperRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
