ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'FOUNDER';
ALTER TYPE public.question_status ADD VALUE IF NOT EXISTS 'CHANGES_REQUESTED';
ALTER TYPE public.question_status ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE public.question_type ADD VALUE IF NOT EXISTS 'MULTI_MCQ';
ALTER TYPE public.review_verdict ADD VALUE IF NOT EXISTS 'CHANGES_REQUESTED';