ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'PRESIDENT';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'VICE_PRESIDENT';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'CREATIVE_HEAD';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'PRE_CLINICAL_HEAD';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'PARA_CLINICAL_HEAD';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'CLINICAL_HEAD';